/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d7dadc",
        "tertiary-fixed-dim": "#4cd6ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#0b1d2d",
        "surface-variant": "#e0e3e5",
        "primary-container": "#1a2b3c",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#b7c8de",
        "on-surface-variant": "#44474c",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001f28",
        "secondary-container": "#0070eb",
        "on-tertiary-fixed-variant": "#004e60",
        "inverse-surface": "#2d3133",
        "background": "#f7fafc",
        "on-tertiary-container": "#009dc1",
        "tertiary-fixed": "#b7eaff",
        "on-surface": "#181c1e",
        "outline-variant": "#c4c6cd",
        "on-primary-fixed-variant": "#38485a",
        "on-primary-container": "#8192a7",
        "on-tertiary": "#ffffff",
        "surface-container": "#ebeef0",
        "primary": "#041627",
        "on-secondary-fixed-variant": "#004493",
        "inverse-on-surface": "#eef1f3",
        "on-background": "#181c1e",
        "surface-bright": "#f7fafc",
        "tertiary-container": "#002e3a",
        "on-error-container": "#93000a",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface": "#f7fafc",
        "secondary-fixed": "#d8e2ff",
        "inverse-primary": "#b7c8de",
        "error": "#ba1a1a",
        "outline": "#74777d",
        "surface-container-low": "#f1f4f6",
        "tertiary": "#001820",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "secondary": "#0058bc",
        "primary-fixed": "#d2e4fb",
        "surface-tint": "#4f6073",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0px 12px 32px rgba(24, 28, 30, 0.06)",
        "ambient-lg": "0px 16px 48px rgba(24, 28, 30, 0.1)",
      },
    },
  },
  plugins: [],
};
